// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;

import java.util.Scanner;
import java.text.DecimalFormat;

public abstract class academicEmployees {
	public static Scanner sc = new Scanner (System.in);
	public static DecimalFormat money = new DecimalFormat ("€0.00");
	
	protected float tax;
	protected float prsi;
	protected float grossPay;
	protected float netPay;
	protected float monthlySalary;

	public void calcTax() {
		float taxLowerCharge = 0.22f;
		float taxHigherCharge = 0.42f;
		float taxBasicCharge;
		float taxSpecialCharge;
	   
		if (grossPay > 40000) {
	    	taxBasicCharge = (40000 / 100) * taxLowerCharge;
	    	taxSpecialCharge = ((grossPay - 40000) / 100) * taxHigherCharge;
	        tax = taxBasicCharge + taxSpecialCharge;
		}
	    else
	    	tax = (grossPay / 100) * taxLowerCharge;
		
	}
	
	public void calcPrsi() {
		prsi = monthlySalary * 0.04f;
		
	}
	
	public void calcNetPay() {
		netPay = grossPay - tax - prsi;
	
	}
	
	public void outPut() {
		System.out.printf("\nHere are your pay details below:\n");
		System.out.printf("\nGrossPay:%23s", money.format(grossPay));
		System.out.printf("\nTax:%28s", money.format(tax));
		System.out.printf("\nPRSI:%27s", money.format(prsi));
		System.out.printf("\nNetPay:%26s", money.format(netPay) + "\n");
		
	}
}
