// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;

import java.util.Scanner;
import java.text.DecimalFormat;
import java.math.BigDecimal;

public abstract class academicEmployees {
	public static Scanner sc = new Scanner (System.in);
	public static DecimalFormat money = new DecimalFormat ("€0.00");
	
	protected float tax;
	protected float prsi;
	protected float grossPay;
	protected float netPay;
	protected float monthlySalary;

	public void calcTax() {
		final float taxLowerCharge = 0.22f;
		final float taxHigherCharge = 0.42f;
		float taxBasicCharge;
		float taxSpecialCharge;
		double sum = 40000/12;
		System.out.print("sum" + sum);
	   
		if (grossPay > 40000/12) {
	    	taxBasicCharge = (40000/12) * taxLowerCharge;
	    		System.out.print("\n"+taxBasicCharge);
	    	taxSpecialCharge = (grossPay - 40000/12) * taxHigherCharge;
	    	System.out.print("\n" + taxSpecialCharge);
	        tax = taxBasicCharge + taxSpecialCharge;
	        System.out.print("\n" + tax);
		}
	    else
	    	tax = grossPay * taxLowerCharge;
		System.out.print("\n" + tax);
		
	}
	
	public void calcPrsi() {
		prsi = grossPay * 0.04f;
		
	}
	
	public void calcNetPay() {
		netPay = grossPay - tax - prsi;
	
	}
	
	public void outPutPayDetails() {
		System.out.printf("\nGrossPay:%23s", money.format(grossPay));
		System.out.printf("\nTax:%28s", money.format(tax));
		System.out.printf("\nPRSI:%27s", money.format(prsi));
		System.out.printf("\nNetPay:%26s", money.format(netPay) + "\n");
		
	}
}


