// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;

import java.util.Scanner;
import java.text.DecimalFormat;

public abstract class academicEmployees {
	public static Scanner sc = new Scanner (System.in);
	public static DecimalFormat money = new DecimalFormat ("€0.00");
	
	// Creating protected type variables to be use via inheritance
	protected float tax;
	protected float prsi;
	protected float grossPay;
	protected float netPay;
	protected float monthlySalary;

	// Method to calculate the tax
	public void calcTax() {
		final float taxLowerCharge = 0.22f;
		final float taxHigherCharge = 0.42f;
		// note ** used Double for precision 
		double taxBasicCharge;
		double taxSpecialCharge;
	   
		// If gross pay is greater than 40000/12 charge at the higher charge as well as the lower charge
		if (grossPay > 3333.33) {
	    	taxBasicCharge = 3333.33 * taxLowerCharge;
	    	taxSpecialCharge = (grossPay - 3333.33) * taxHigherCharge;
	        tax = (float) (taxBasicCharge + taxSpecialCharge); 
		}
	    else
	    	tax = grossPay * taxLowerCharge;
			
	}
	
	// Method to calculate the prsi
	public void calcPrsi() {
		final float prsiCharge = 0.04f;
		prsi = grossPay * prsiCharge;
		
	}
	
	// Method to calculate the net pay
	public void calcNetPay() {
		netPay = grossPay - tax - prsi;
	
	}
	
	// Method to output the main pay details
	public void outPutPayDetails() {
		System.out.printf("\nGrossPay:%23s", money.format(grossPay));
		System.out.printf("\nTax:%28s", money.format(tax));
		System.out.printf("\nPRSI:%27s", money.format(prsi));
		System.out.printf("\nNetPay:%26s", money.format(netPay) + "\n");
		
	}
}



