// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;

import java.util.Scanner;
import java.text.DecimalFormat;

public class fullTime extends teacher {
	public static Scanner sc = new Scanner (System.in);
	public static DecimalFormat money = new DecimalFormat ("€0.00");
	
	public float scalePointsPay;
	public float daysAbsentDeductions;
	public int scalePoints;
	public int daysAbsent;


	public void calcScalePointsPay() {
		do {
			System.out.print("\nEnter your Points on Scale: ");
			scalePoints = sc.nextInt();
			if (scalePoints > 4 || scalePoints < 0)
				System.err.println("\nPlease pick a number on the scale between 0 to 4.");
			else if (scalePoints == 1)
				scalePointsPay += 426.67;
			else if (scalePoints == 2)
				scalePointsPay += 565.75;
			else if (scalePoints == 3)
				scalePointsPay += 666.58;
			else
				scalePointsPay += 750;
		} while (scalePoints > 4 || scalePoints < 0);
	}

	public void calcDeductions() {
		System.out.print("\nEnter the number of days absent: ");
		daysAbsent = sc.nextInt();
		
		daysAbsentDeductions = daysAbsent * 62.68f;
	}

	public void calcGrossPay() {
		monthlySalary = 3343.58f;
		grossPay = monthlySalary + examScriptsPay + scalePointsPay - daysAbsentDeductions;
	}
	
	public void outPutWorkDetails() {
		System.out.printf("\nDocked Pay: " + daysAbsent +" absent days @ €62.68 per day = " + money.format(daysAbsentDeductions)
						  + "\nPoints on Scale: " + scalePoints + " points = " + money.format(scalePointsPay)
						  + "\nSet Full Time Monthly Salary: " + money.format(monthlySalary) + "\n");
		
	}
}
