// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;
import java.util.Scanner;

public class principle extends academicEmployees {
	public static Scanner sc = new Scanner (System.in);
	
	public int workCapcityPay;

	public void calcBonusPay() {
		System.out.print("\nEnter the amount of Teachers in your school: ");
		int numOfEmps = sc.nextInt();
		
		if (numOfEmps > 200)
			workCapcityPay += 1196.67;
		else if (numOfEmps > 100) 
			workCapcityPay += 1019.83;
		else if (numOfEmps > 10) 
			workCapcityPay += 869.33;
		else 
			workCapcityPay += 775.83;
	}
	
	public void calcGrossPay() {
		monthlySalary = 5000;
		grossPay = workCapcityPay + monthlySalary;
	}
}
