// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package academicEmployees;

import java.util.Scanner;
import java.text.DecimalFormat;

public class principal extends academicEmployees {
	public static Scanner sc = new Scanner (System.in);
	public static DecimalFormat money = new DecimalFormat ("€0.00");
	
	// Creating public type variables
	public float workCapcityPay;
	public int numOfTeachers;

	// Method to calculate the teacher capacity pay
	public void calcTeacherCapacityPay() {
		System.out.print("\nEnter the number of Teachers in your school: ");
		numOfTeachers = sc.nextInt();
		
		if (numOfTeachers > 200)
			workCapcityPay += 1196.67f;
		else if (numOfTeachers > 100) 
			workCapcityPay += 1019.83f;
		else if (numOfTeachers > 10) 
			workCapcityPay += 869.33f;
		else 
			workCapcityPay += 775.83f;
	}


	// Method to calculate the the unique gross pay for the Principal
	public void calcGrossPay() {
		monthlySalary = 5000;
		grossPay = workCapcityPay + monthlySalary;
	}
	
	// Method to calculate the specific work details to the Principal
	public void outPutWorkDetails() {
		System.out.printf("\nNumber of Teachers: " + numOfTeachers + ", capacity bonus = " + money.format(workCapcityPay)
		+ "\nSet Principal Monthly Salary: " + money.format(monthlySalary)  + "\n");

	}
}
